# Generated by Django 4.2 on 2023-07-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course',
            new_name='paid_course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson',
            new_name='paid_lesson',
        ),
    ]
